[package]
name = "solc-rs"
version = "0.1.0"
authors = ["Santiago Palladino <spalladino@gmail.com>"]
edition = "2018"

[dependencies]
solc = { git = "https://github.com/axic/solc-rust" }
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"